// ── WINDOW MANAGER ─────────────────────────────────────────────
const WM=(()=>{
  const wins=new Map();let z=200,active=null;
  const el=id=>document.getElementById('win_'+id);
  function focus(id){if(active===id)return;if(active){el(active)?.classList.remove('focused');document.querySelector(`.tb-app[data-wid="${active}"]`)?.classList.remove('active');}active=id;const e=el(id);if(!e)return;e.style.zIndex=++z;e.classList.add('focused');document.querySelector(`.tb-app[data-wid="${id}"]`)?.classList.add('active');}
  function create({id,title,width,height,content,onMount,imgSrc,iconKey}){if(wins.has(id)){const s=wins.get(id);s.minimized?restore(id):focus(id);return;}const off=(wins.size%8)*28;const L=Math.max(20,(window.innerWidth-width)/2+off);const T=Math.max(10,(window.innerHeight-height)/2+off);const e=document.createElement('div');e.className='window';e.id='win_'+id;e.style.cssText=`left:${L}px;top:${T}px;width:${width}px;height:${height}px;z-index:${++z}`;const iH=imgSrc?`<div class="win-icon-sm"><img src="${imgSrc}" onerror="this.style.display='none'" alt=""></div>`:(ICO[iconKey]?`<div class="win-icon-sm" style="width:17px;height:17px">${ICO[iconKey]()}</div>`:'');e.innerHTML=`<div class="win-titlebar"><div class="traffic"><button class="tb cl"></button><button class="tb mn"></button><button class="tb mx"></button></div>${iH}<div class="win-title">${title}</div></div><div class="win-body">${content}</div><div class="rh n"></div><div class="rh s"></div><div class="rh e"></div><div class="rh w"></div><div class="rh se"></div><div class="rh sw"></div><div class="rh ne"></div><div class="rh nw"></div>`;e.style.opacity='0';e.style.transform='scale(0.9)translateY(18px)';document.body.appendChild(e);wins.set(id,{minimized:false,maximized:false,saved:null});requestAnimationFrame(()=>{e.style.transition='opacity .25s ease,transform .32s cubic-bezier(.2,1.2,.3,1)';e.style.opacity='1';e.style.transform='scale(1)translateY(0)';setTimeout(()=>e.style.transition='',380);});const[cl,mn,mx]=e.querySelectorAll('.tb');cl.onclick=ev=>{ev.stopPropagation();close(id);};mn.onclick=ev=>{ev.stopPropagation();minimize(id);};mx.onclick=ev=>{ev.stopPropagation();toggleMax(id);};e.querySelector('.win-titlebar').addEventListener('dblclick',ev=>{if(!ev.target.classList.contains('tb'))toggleMax(id);});e.addEventListener('mousedown',ev=>{if(!ev.target.classList.contains('tb'))focus(id);});_drag(e,e.querySelector('.win-titlebar'),id);e.querySelectorAll('.rh').forEach(h=>_resize(e,h,id));_addTb(id,title,imgSrc,iconKey);focus(id);if(onMount)setTimeout(()=>onMount(e),14);}
  function close(id){const e=el(id);if(!e)return;e.style.transition='opacity .2s ease,transform .22s ease';e.style.opacity='0';e.style.transform='scale(0.88)translateY(18px)';setTimeout(()=>{e.remove();wins.delete(id);_removeTb(id);if(active===id)active=null;},220);}
  function minimize(id){const e=el(id),s=wins.get(id);if(!e||!s)return;s.minimized=true;e.style.transition='opacity .22s ease,transform .25s cubic-bezier(.4,0,.6,1)';e.style.opacity='0';e.style.transform='scale(0.5)translateY(220px)';setTimeout(()=>e.style.visibility='hidden',260);document.querySelector(`.tb-app[data-wid="${id}"]`)?.classList.remove('active');if(active===id)active=null;}
  function restore(id){const e=el(id),s=wins.get(id);if(!e||!s)return;s.minimized=false;e.style.visibility='visible';e.style.opacity='0';e.style.transform='scale(0.82)translateY(40px)';requestAnimationFrame(()=>{e.style.transition='opacity .25s ease,transform .32s cubic-bezier(.2,1.2,.3,1)';e.style.opacity='1';e.style.transform='scale(1)translateY(0)';setTimeout(()=>e.style.transition='',360);});focus(id);}
  function toggleMax(id){const e=el(id),s=wins.get(id);if(!e||!s)return;e.style.transition='all .3s cubic-bezier(.2,1,.3,1)';if(!s.maximized){s.saved={l:e.style.left,t:e.style.top,w:e.style.width,h:e.style.height};e.style.left='0';e.style.top='0';e.style.width='100vw';e.style.height='100vh';e.classList.add('maximized');s.maximized=true;}else{const r=s.saved;e.style.left=r.l;e.style.top=r.t;e.style.width=r.w;e.style.height=r.h;e.classList.remove('maximized');s.maximized=false;}setTimeout(()=>e.style.transition='',320);}
  function _drag(win,bar,id){let sx,sy,sl,st,on=false;bar.addEventListener('mousedown',e=>{if(e.target.classList.contains('tb'))return;if(wins.get(id)?.maximized)return;on=true;sx=e.clientX;sy=e.clientY;sl=win.offsetLeft;st=win.offsetTop;e.preventDefault();focus(id);});document.addEventListener('mousemove',e=>{if(!on)return;win.style.left=(sl+e.clientX-sx)+'px';win.style.top=Math.max(0,st+e.clientY-sy)+'px';});document.addEventListener('mouseup',()=>on=false);}
  function _resize(win,handle,id){const dir=[...handle.classList].find(c=>/^(n|s|e|w|se|sw|ne|nw)$/.test(c));if(!dir)return;let sx,sy,sw,sh,sl,st,on=false;handle.addEventListener('mousedown',e=>{if(wins.get(id)?.maximized)return;on=true;sx=e.clientX;sy=e.clientY;sw=win.offsetWidth;sh=win.offsetHeight;sl=win.offsetLeft;st=win.offsetTop;e.preventDefault();e.stopPropagation();});document.addEventListener('mousemove',e=>{if(!on)return;const dx=e.clientX-sx,dy=e.clientY-sy,mW=300,mH=180;if(dir.includes('e'))win.style.width=Math.max(mW,sw+dx)+'px';if(dir.includes('s'))win.style.height=Math.max(mH,sh+dy)+'px';if(dir.includes('n')){const nH=Math.max(mH,sh-dy);win.style.height=nH+'px';win.style.top=(st+sh-nH)+'px';}if(dir.includes('w')){const nW=Math.max(mW,sw-dx);win.style.width=nW+'px';win.style.left=(sl+sw-nW)+'px';}});document.addEventListener('mouseup',()=>on=false);}
  function _addTb(id,title,imgSrc,iconKey){const e=document.createElement('div');e.className='tb-app open';e.dataset.wid=id;const iH=imgSrc?`<img src="${imgSrc}" width="28" height="28" onerror="this.style.display='none'" alt="">`:`<div style="width:28px;height:28px;display:flex;align-items:center;justify-content:center">${ICO[iconKey]?ICO[iconKey]():''}</div>`;e.innerHTML=`${iH}<div class="tb-tip">${title}</div><div class="tb-dot"></div>`;e.addEventListener('click',()=>{const s=wins.get(id);if(!s)return;s.minimized?restore(id):(active===id?minimize(id):focus(id));});e.addEventListener('contextmenu',ev=>{ev.preventDefault();ctxMenu(ev.clientX,ev.clientY,[{label:'Restore',fn:()=>restore(id)},{label:'Maximize',fn:()=>toggleMax(id)},{sep:true},{label:'Close',fn:()=>close(id),danger:true}]);});document.getElementById('tb-apps').appendChild(e);}
  function _removeTb(id){const e=document.querySelector(`.tb-app[data-wid="${id}"]`);if(!e)return;e.style.transition='all .18s ease';e.style.opacity='0';e.style.transform='scale(0.5)';setTimeout(()=>e.remove(),180);}
  return{create,close,minimize,restore,toggleMax,focus};
})();

